import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { parseConfigFileTextToJson } from "typescript";

const serverEntryNames = ["ssr.mjs", "index.mjs"] as const;
let compiledServerEntry = serverEntryNames[0];
let compiledServer: string | undefined;
for (const entry of serverEntryNames) {
  try {
    compiledServer = await readFile(resolve(process.cwd(), ".output/server/_ssr", entry), "utf8");
    compiledServerEntry = entry;
    break;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
}
if (!compiledServer) throw new Error("The compiled Bento server entry is missing.");
const workerEntryPath = resolve(process.cwd(), ".output/server/worker.mjs");
const generatedWranglerPath = resolve(process.cwd(), ".output/server/wrangler.json");
const sourceWranglerPath = resolve(process.cwd(), "wrangler.jsonc");

if (!compiledServer.includes("async queue(batch, env")) {
  throw new Error(
    "The compiled Bento server does not export its queue consumer. Refusing to create a deployable Worker entry.",
  );
}

if (!compiledServer.includes("async scheduled(controller")) {
  throw new Error(
    "The compiled Bento server does not export its scheduled email processor. Refusing to create a deployable Worker entry.",
  );
}

await writeFile(
  workerEntryPath,
  [
    "// Generated by scripts/write-worker-entry.ts. Do not edit.",
    `import server from "./_ssr/${compiledServerEntry}";`,
    "function bindRuntime(request, env, context) {",
    "  globalThis.__env__ = env;",
    '  request.runtime ??= { name: "cloudflare" };',
    "  request.runtime.cloudflare = {",
    "    ...request.runtime.cloudflare,",
    "    env,",
    "    context,",
    "  };",
    "  request.waitUntil = context?.waitUntil.bind(context);",
    "  return request;",
    "}",
    "export default {",
    "  fetch(request, env, context) {",
    "    return server.fetch(bindRuntime(request, env, context));",
    "  },",
    "  queue(batch, env, context) {",
    "    globalThis.__env__ = env;",
    "    return server.queue(batch, env, context);",
    "  },",
    "  scheduled(controller, env, context) {",
    "    globalThis.__env__ = env;",
    "    return server.scheduled(controller, env, context);",
    "  },",
    "};",
    "",
  ].join("\n"),
  "utf8",
);

const generatedWrangler = JSON.parse(await readFile(generatedWranglerPath, "utf8")) as Record<
  string,
  unknown
>;
const sourceWranglerResult = parseConfigFileTextToJson(
  sourceWranglerPath,
  await readFile(sourceWranglerPath, "utf8"),
);
if (sourceWranglerResult.error) throw new Error("wrangler.jsonc is not valid JSONC.");
const sourceWrangler = sourceWranglerResult.config as Record<string, unknown>;
const safeDeploymentKeys = [
  "ai",
  "assets",
  "browser",
  "images",
  "compatibility_date",
  "compatibility_flags",
  "no_bundle",
  "observability",
  "preview_urls",
  "queues",
  "r2_buckets",
  "ratelimits",
  "rules",
  "triggers",
  "workers_dev",
] as const;
const safeDeploymentConfig = Object.fromEntries(
  safeDeploymentKeys.flatMap((key) => (key in sourceWrangler ? [[key, sourceWrangler[key]]] : [])),
);
Object.assign(generatedWrangler, safeDeploymentConfig, {
  main: "worker.mjs",
  assets: {
    ...((safeDeploymentConfig.assets as Record<string, unknown> | undefined) || {}),
    directory: "../public",
  },
});
await writeFile(generatedWranglerPath, `${JSON.stringify(generatedWrangler, null, 2)}\n`, "utf8");

console.log(
  "Generated Cloudflare Worker entry and configured Wrangler to forward fetch, queue, and scheduled handlers.",
);
