-- Private reliability accounting for paid social-card previews.
create table public.social_preview_attempts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  platform text not null,
  source text not null,
  attempt_number smallint not null,
  outcome text not null,
  duration_ms integer not null,
  browser_ms integer,
  used_bright boolean not null default false,
  constraint social_preview_attempts_platform_check check (
    platform in (
      'instagram', 'twitter', 'tiktok', 'linkedin', 'youtube',
      'github', 'gitlab', 'reddit', 'bluesky', 'mastodon'
    )
  ),
  constraint social_preview_attempts_source_check check (length(source) between 1 and 64),
  constraint social_preview_attempts_attempt_check check (attempt_number between 1 and 4),
  constraint social_preview_attempts_outcome_check check (
    outcome in ('success', 'unavailable', 'timeout', 'rate_limited', 'blocked', 'parse_error', 'error')
  ),
  constraint social_preview_attempts_duration_check check (duration_ms between 0 and 300000),
  constraint social_preview_attempts_browser_check check (browser_ms is null or browser_ms between 0 and 300000)
);

create index social_preview_attempts_created_idx
  on public.social_preview_attempts(created_at desc);
create index social_preview_attempts_platform_source_created_idx
  on public.social_preview_attempts(platform, source, created_at desc);

create table public.social_preview_budgets (
  provider text not null,
  period_start date not null,
  used bigint not null default 0,
  updated_at timestamptz not null default now(),
  primary key (provider, period_start),
  constraint social_preview_budgets_provider_check check (provider in ('browser_run', 'bright_data')),
  constraint social_preview_budgets_used_check check (used >= 0)
);

alter table public.social_preview_attempts enable row level security;
alter table public.social_preview_budgets enable row level security;
revoke all on public.social_preview_attempts from public, anon, authenticated;
revoke all on public.social_preview_budgets from public, anon, authenticated;
grant all on public.social_preview_attempts to service_role;
grant all on public.social_preview_budgets to service_role;
revoke all on sequence public.social_preview_attempts_id_seq from public, anon, authenticated;
grant usage, select on sequence public.social_preview_attempts_id_seq to service_role;

create or replace function public.claim_social_preview_budget(
  p_provider text,
  p_period_start date,
  p_units bigint,
  p_limit bigint
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  claimed boolean;
begin
  if p_provider not in ('browser_run', 'bright_data')
     or p_units <= 0
     or p_limit <= 0
     or p_units > p_limit then
    return false;
  end if;

  insert into public.social_preview_budgets(provider, period_start, used)
  values (p_provider, p_period_start, p_units)
  on conflict (provider, period_start) do update
    set used = public.social_preview_budgets.used + excluded.used,
        updated_at = now()
    where public.social_preview_budgets.used + excluded.used <= p_limit
  returning true into claimed;

  return coalesce(claimed, false);
end;
$$;

revoke all on function public.claim_social_preview_budget(text, date, bigint, bigint)
  from public, anon, authenticated;
grant execute on function public.claim_social_preview_budget(text, date, bigint, bigint)
  to service_role;

create or replace function public.adjust_social_preview_budget(
  p_provider text,
  p_period_start date,
  p_delta bigint
)
returns void
language sql
security definer
set search_path = public, pg_temp
as $$
  update public.social_preview_budgets
  set used = greatest(0, used + p_delta),
      updated_at = now()
  where provider = p_provider
    and period_start = p_period_start;
$$;

revoke all on function public.adjust_social_preview_budget(text, date, bigint)
  from public, anon, authenticated;
grant execute on function public.adjust_social_preview_budget(text, date, bigint)
  to service_role;
