// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import { RequestHttpError } from "@/lib/request-security.server";
import type { Database } from "./types";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new RequestHttpError(401, "Unauthorized");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new RequestHttpError(401, "Unauthorized");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new RequestHttpError(401, "Unauthorized");
    }

    const match = authHeader.match(/^Bearer ([A-Za-z0-9._~+/-]{20,8192})$/);
    if (!match) throw new RequestHttpError(401, "Unauthorized");
    const token = match[1];

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new RequestHttpError(401, "Unauthorized");
    }

    if (!data.claims.sub) {
      throw new RequestHttpError(401, "Unauthorized");
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
        accessToken: token,
      },
    });
  },
);
